import{S as w,a as v,i as n}from"./assets/vendor-DXKtl-Fy.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const u=document.querySelector(".load-more"),d=document.querySelector(".loader"),f=document.querySelector(".gallery"),b=new w(".gallery a",{});function p(e){const t=e.map(P).join("");f.insertAdjacentHTML("beforeend",t),e.length>0&&b.refresh()}function S(){f.innerHTML=""}function m(){d.classList.remove("visually-hidden")}function h(){d.classList.add("visually-hidden")}function P({webformatURL:e,largeImageURL:t,tags:s,likes:i,views:r,comments:o,downloads:a}){return`
    <li class="gallery-item">
      <a href="${t}">
        <img src="${e}" alt="${s}" loading="lazy">
      </a>
      <ul class="meta">
        <li><p>Likes</p><span>${i??0}</span></li>
        <li><p>Views</p><span>${r??0}</span></li>
        <li><p>Comments</p><span>${o??0}</span></li>
        <li><p>Downloads</p><span>${a??0}</span></li>
      </ul>
    </li>`}function R(){u.classList.remove("visually-hidden")}function g(){u.classList.add("visually-hidden")}const E=v.create({baseURL:"https://pixabay.com/api/",timeout:5e3}),q="52280453-e49fee1d7ac9fb337b56d8047";async function y(e,t){const s={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{return(await E.get("",{params:s})).data}catch(i){return n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),console.error("Pixabay API error:",i),{hits:[],totalHits:0}}}const M=document.querySelector(".form"),$=document.querySelector(".load-more");let c="",l=1,B=0;M.addEventListener("submit",H);$.addEventListener("click",O);async function H(e){if(e.preventDefault(),c=e.currentTarget.elements["search-text"].value.trim(),l=1,!c){n.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}S(),g(),m();try{const t=await y(c,l);if(!t.hits.length){n.info({title:"No Results",message:"No images found. Try another keyword.",position:"topRight"});return}B=t.totalHits,p(t.hits),L(t)}catch(t){n.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"}),console.error("Search error:",t)}finally{h()}}async function O(){l+=1,m();try{const e=await y(c,l);p(e.hits),x(),L(e)}catch(e){n.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error("Load more error:",e)}finally{h()}}function L(e){const t=Math.ceil(e.totalHits/15);l>=t||e.hits.length<15?(g(),n.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight"})):R()}function x(){const e=document.querySelector(".gallery-item");if(!e)return;const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
