import{S as w,a as R,i as a}from"./assets/vendor-DXKtl-Fy.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const h=document.querySelector(".form"),f=document.querySelector(".load-more"),m=document.querySelector(".loader"),g=document.querySelector(".gallery"),P=new w(".gallery a",{});function y(o){const t=o.map(E).join("");g.insertAdjacentHTML("beforeend",t),o.length>0&&P.refresh()}function p(){g.innerHTML=""}function L(){m.classList.remove("visually-hidden")}function b(){m.classList.add("visually-hidden")}function E({webformatURL:o,largeImageURL:t,tags:i,likes:s,views:e,comments:r,downloads:n}){return`
    <li class="gallery-item">
      <a href="${t}">
        <img src="${o}" alt="${i}" loading="lazy">
      </a>
      <ul class="meta">
        <li><p>Likes</p><span>${s??0}</span></li>
        <li><p>Views</p><span>${e??0}</span></li>
        <li><p>Comments</p><span>${r??0}</span></li>
        <li><p>Downloads</p><span>${n??0}</span></li>
      </ul>
    </li>`}function S(){f.classList.remove("visually-hidden")}function c(){f.classList.add("visually-hidden")}const q=R.create({baseURL:"https://pixabay.com/api/",timeout:5e3}),M="52280453-e49fee1d7ac9fb337b56d8047";console.log("52280453-e49fee1d7ac9fb337b56d8047");async function v(o,t){const i={key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{return(await q.get("",{params:i})).data}catch(s){return a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),console.error("Pixabay API error:",s),{hits:[],totalHits:0}}}let u="",l=1,d=0;h.addEventListener("submit",$);f.addEventListener("click",B);async function $(o){if(o.preventDefault(),c(),u=o.currentTarget.elements["search-text"].value.trim(),l=1,!u)return p(),h.reset(),a.error({title:"Error",message:"Please enter a search term!",position:"topRight"});p(),c(),L();const t=await v(u,l);if(b(),t.hits.length===0)return a.info({title:"No Results",message:"No images found. Try another keyword.",position:"topRight"});d=t.totalHits,y(t.hits),t.hits.length===15&&d>15?S():(c(),a.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight"}))}async function B(){l+=1,L();const o=await v(u,l);b(),y(o.hits),H();const t=Math.ceil(d/15);l>=t&&(c(),a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}function H(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
